project:
  type: book
  output-dir: ../docs
  
book:
  title: "Nittany ARC Station Guide"
  subtitle: "Version 2024-07-12-1135"
  author: "Rick Gilmore W3TM"
  output-file: "NARC-Clubhouse-Guide"
  cover-image: "include/img/60-ft-tower-west.jpg"
  downloads: [pdf]
  chapters:
    - index.qmd
    - logistics.qmd
    - part: stations.qmd
      chapters:
        - narc1.qmd
        - narc2.qmd
        - narc3.qmd    
        - packet_aprs.qmd
    - part: rigs.qmd
      chapters:
        - icom-ic-7610.qmd
        - flex-6400M.qmd
        - ic-718.qmd
        - kenwood-D710.qmd
    - part: "Other resources"
      chapters:
        - antennas.qmd
        - wifi-internet.qmd
        - remote-operations.qmd
        - test-suite.qmd
        - software.qmd
        - logging.qmd
  repo-url: https://github.com/nittany-amateur-radio-club/station
  repo-actions: [edit, issue]
  repo-subdir: src
  
format:
  html:
    theme: cosmo
    number-sections: false
    date-modified: last-modified
    fontsize: 1.2em
